# Cloud Build configuration for Reflectica Backend
# This file defines the steps to build and deploy the backend to Cloud Run
steps:
  # Step 1: Build the Docker image with two tags (commit SHA and latest)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/reflectica-backend/reflectica-backend:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/reflectica-backend/reflectica-backend:latest'
      - '.'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/reflectica-backend/reflectica-backend']

  # Step 3: Deploy to Cloud Run with all configurations
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'reflectica-backend'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/reflectica-backend/reflectica-backend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--set-secrets=OPENAI_API_KEY=openai-api-key:latest,PINECONE_API_KEY=pinecone-api-key:latest,AWS_ACCESS_KEY_ID=aws-access-key-id:latest,AWS_SECRET_ACCESS_KEY=aws-secret-access-key:latest,GMAIL_PASS_KEY=gmail-pass-key:latest,ELEVENLABS_API_KEY=elevenlabs-api-key:latest,FIREBASE_PRIVATE_KEY=firebase-private-key:latest'
      - '--set-env-vars=NODE_ENV=production,FIREBASE_PROJECT_ID=reflectica1,FIREBASE_CLIENT_EMAIL=firebase-adminsdk-6mg6n@reflectica1.iam.gserviceaccount.com,FIREBASE_CLIENT_ID=118057908918123348199,FIREBASE_AUTH_URI=https://accounts.google.com/o/oauth2/auth,FIREBASE_TOKEN_URI=https://oauth2.googleapis.com/token,FIREBASE_AUTH_PROVIDER_CERT_URL=https://www.googleapis.com/oauth2/v1/certs,FIREBASE_CLIENT_CERT_URL=https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-6mg6n%40reflectica1.iam.gserviceaccount.com,FIREBASE_UNIVERSAL_DOMAIN=googleapis.com,PINECONE_ENVIRONMENT=gcp-starter'

# Build configuration
timeout: 1200s # 20 minutes timeout
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' # Use faster machine for builds

# Substitutions (optional - for advanced use)
substitutions:
  _SERVICE_NAME: reflectica-backend
  _REGION: us-central1